# Generated by Django 5.1.6 on 2025-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0003_paciente_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_internacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
