# Generated by Django 5.1.6 on 2025-02-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0004_alter_paciente_data_internacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='analise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
